server.port=8080
server.address=0.0.0.0

rmi.host=10.153.90.35
rmi.port=1806
rmi.name=restaurante

app.frontend.path=./frontEnd/,file:../frontEnd/
spring.web.resources.static-locations=file:${app.frontend.path}

app.menu-config=classpath:menu-config.json
app.menu.cache-seconds=15
app.orders.payment-methods=Efectivo,Nequi,Transferencia

app.cors.allowed-origins=*
